/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IPZappWindow;

import static IPZappWindow.EditLabelersListWindow.labellersListFile;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.*;
import org.json.*;
import java.sql.*;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author lenovo
 */
public class labellerApp extends javax.swing.JFrame {
    private boolean ifEditLabellersOpened = false;
    private boolean ifConnected = false;
    private List labellersList = new ArrayList<Labeller>();
    private DefaultListModel computerConfigListModel = new DefaultListModel();
    private DefaultListModel labellerConfigListModel = new DefaultListModel();
    private DefaultListModel labellerConfigStatsListModel = new DefaultListModel();
    private List computerConfigList = new ArrayList<Configuration>();
    private List labellerConfigList = new ArrayList<Configuration>();
    private List labellerConfigStatsList = new ArrayList<ConfigurationStats>();
    private String chosenLabellerIPAddress;
    private String SQLDriver = "com.mysql.cj.jdbc.Driver";
    private ConnectionPool connectionPool;
    private String DATABASE_USER = "pracownik";
    private String DATABASE_PASSWORD = "etykieciarka";
    JPanel glass = new JPanel(new GridLayout(0, 1)); 
    JLabel padding = new JLabel();
    Timer timer;

    /**
     * Creates new form labellerApp
     */
    public labellerApp() {
        initComponents();
        updateLabellersComboBox();
        updateComputerConfigList();
        glass.setOpaque(false);
        glass.add(padding);
        glass.addMouseListener(new MouseAdapter() {});
        glass.addMouseMotionListener(new MouseMotionAdapter() {});
        glass.addKeyListener(new KeyAdapter() {});
        this.setGlassPane(glass);
        this.addWindowListener(new WindowAdapter() 
        {
            public void windowClosing(WindowEvent e) 
            {
                disconnect();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editLabListButton = new javax.swing.JButton();
        newConfButton = new javax.swing.JButton();
        confStatsPane = new javax.swing.JTabbedPane();
        confPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        computerConfigListWindow = new javax.swing.JList<>(computerConfigListModel);
        downloadConfButton = new javax.swing.JButton();
        removeLabelConfButton = new javax.swing.JButton();
        sendConfButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        labellerConfigListWindow = new javax.swing.JList<>(labellerConfigListModel);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        removeCompConfButton = new javax.swing.JButton();
        editConfButton = new javax.swing.JButton();
        updateConfListButton = new javax.swing.JButton();
        statsPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        statsConfigListWindow = new javax.swing.JList<>(labellerConfigStatsListModel);
        jLabel2 = new javax.swing.JLabel();
        startDateTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        stopDateTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        info1TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        info2TextField = new javax.swing.JTextField();
        info3TextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        updateStatsButton = new javax.swing.JButton();
        connectPanel = new javax.swing.JPanel();
        labellersComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        connStatusPanel = new StatusPanel();
        connectButton = new javax.swing.JButton();
        disconnectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Labellers manager");
        setIconImage(new ImageIcon("label printer.png").getImage());
        setLocationByPlatform(true);
        setResizable(false);

        editLabListButton.setText("Edit labellers list");
        editLabListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editLabListButtonActionPerformed(evt);
            }
        });

        newConfButton.setText("Create new cofiguration");
        newConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newConfButtonActionPerformed(evt);
            }
        });

        confStatsPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        computerConfigListWindow.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(computerConfigListWindow);

        downloadConfButton.setText("Download");
        downloadConfButton.setToolTipText("Download configuration from labeller");
        downloadConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadConfButtonActionPerformed(evt);
            }
        });

        removeLabelConfButton.setText("Remove");
        removeLabelConfButton.setToolTipText("Remove configuration from labeller");
        removeLabelConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLabelConfButtonActionPerformed(evt);
            }
        });

        sendConfButton.setText("Send");
        sendConfButton.setToolTipText("Send configuration to labeller");
        sendConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendConfButtonActionPerformed(evt);
            }
        });

        labellerConfigListWindow.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(labellerConfigListWindow);

        jLabel6.setText("Configurations on labeller");

        jLabel7.setText("Configurations on computer");

        removeCompConfButton.setText("Remove");
        removeCompConfButton.setToolTipText("Remove configuration from computer");
        removeCompConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCompConfButtonActionPerformed(evt);
            }
        });

        editConfButton.setText("Edit");
        editConfButton.setToolTipText("Edit configuration");
        editConfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editConfButtonActionPerformed(evt);
            }
        });

        updateConfListButton.setText("Update");
        updateConfListButton.setToolTipText("Download configuration from labeller");
        updateConfListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateConfListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout confPanelLayout = new javax.swing.GroupLayout(confPanel);
        confPanel.setLayout(confPanelLayout);
        confPanelLayout.setHorizontalGroup(
            confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(confPanelLayout.createSequentialGroup()
                        .addComponent(editConfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeCompConfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendConfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(confPanelLayout.createSequentialGroup()
                        .addComponent(downloadConfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateConfListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeLabelConfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3)
                    .addGroup(confPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(confPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        confPanelLayout.setVerticalGroup(
            confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(downloadConfButton)
                    .addComponent(removeLabelConfButton)
                    .addComponent(updateConfListButton))
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(confPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editConfButton)
                    .addComponent(removeCompConfButton)
                    .addComponent(sendConfButton)))
        );

        confStatsPane.addTab("Configurations", confPanel);

        statsConfigListWindow.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        statsConfigListWindow.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                statsConfigListWindowValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(statsConfigListWindow);

        jLabel2.setText("Start date:");

        startDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Stop date:");

        jLabel4.setText("Information 1:");

        jLabel5.setText("Information 2:");

        jLabel8.setText("Information 3:");

        updateStatsButton.setText("Update");
        updateStatsButton.setToolTipText("");
        updateStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStatsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statsPanelLayout = new javax.swing.GroupLayout(statsPanel);
        statsPanel.setLayout(statsPanelLayout);
        statsPanelLayout.setHorizontalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addGroup(statsPanelLayout.createSequentialGroup()
                        .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(info3TextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info2TextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(startDateTextField)
                            .addComponent(stopDateTextField)
                            .addComponent(info1TextField))))
                .addContainerGap())
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(updateStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        statsPanelLayout.setVerticalGroup(
            statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(stopDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(info1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(info2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(statsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(info3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateStatsButton)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        confStatsPane.addTab("Statistics", statsPanel);

        connectPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Choose labeller to connect:");

        javax.swing.GroupLayout connStatusPanelLayout = new javax.swing.GroupLayout(connStatusPanel);
        connStatusPanel.setLayout(connStatusPanelLayout);
        connStatusPanelLayout.setHorizontalGroup(
            connStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );
        connStatusPanelLayout.setVerticalGroup(
            connStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        disconnectButton.setText("Disconnect");
        disconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disconnectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout connectPanelLayout = new javax.swing.GroupLayout(connectPanel);
        connectPanel.setLayout(connectPanelLayout);
        connectPanelLayout.setHorizontalGroup(
            connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, connectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(connectPanelLayout.createSequentialGroup()
                        .addComponent(labellersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(connStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(connectPanelLayout.createSequentialGroup()
                        .addGroup(connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(connectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(disconnectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(connectPanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        connectPanelLayout.setVerticalGroup(
            connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(connectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(connStatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labellersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(disconnectButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newConfButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editLabListButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confStatsPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newConfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editLabListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(confStatsPane)
            .addComponent(connectPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        confStatsPane.getAccessibleContext().setAccessibleName("Konfiguracje");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editLabListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editLabListButtonActionPerformed
        if(ifEditLabellersOpened == false) {
                EditLabelersListWindow window = new EditLabelersListWindow();
                ifEditLabellersOpened = true;
                window.setVisible(true);
                window.addWindowListener(new WindowAdapter(){
                    public void windowClosing(WindowEvent e) 
                    {
                        ifEditLabellersOpened = false;
                        updateLabellersComboBox();
                    }
                });
        }
    }//GEN-LAST:event_editLabListButtonActionPerformed

    private void newConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newConfButtonActionPerformed
        CreateNewConfWindow newWindow = new CreateNewConfWindow();
        newWindow.addWindowListener(new WindowAdapter(){
            public void windowClosing(WindowEvent e) 
            {
                updateComputerConfigList();
            }
        });
        newWindow.setVisible(true);
    }//GEN-LAST:event_newConfButtonActionPerformed

    private void removeLabelConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLabelConfButtonActionPerformed
        int selectedIndex = labellerConfigListWindow.getSelectedIndex();
        if(selectedIndex == -1)
            return;
        String message = "Are you sure you want to remove " + ((Configuration)labellerConfigList.get(selectedIndex)).getName() + " configuration from labeller memory?";
        int answer = JOptionPane.showConfirmDialog(rootPane, message, "Warning", JOptionPane.YES_NO_OPTION);
        if(answer == 0 && ifConnected)
        {
            glass.setVisible(true);
            padding.requestFocus();
            removeConfigurationFromLabeller(selectedIndex);
            updateLabellerConfigList();
        }
        startGlassTimer();
    }//GEN-LAST:event_removeLabelConfButtonActionPerformed

    private void removeCompConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCompConfButtonActionPerformed
        String selectedConf = computerConfigListWindow.getSelectedValue();
        int selectedConfIndex = computerConfigListWindow.getSelectedIndex();
        if(selectedConf == null)
            return;
        computerConfigList.remove(selectedConfIndex);
        File fileToRemove = new File(CreateNewConfWindow.configurationsListDir, new String(selectedConf + ".labconf"));
        if(fileToRemove.exists())
        {
            fileToRemove.delete();
        }
        updateComputerConfigList();
    }//GEN-LAST:event_removeCompConfButtonActionPerformed

    private void editConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editConfButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editConfButtonActionPerformed

    private void sendConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendConfButtonActionPerformed
        int selectedConfIndex = computerConfigListWindow.getSelectedIndex();
        if(selectedConfIndex == -1)
            return;
        if(ifConnected)
        {
            glass.setVisible(true);
            padding.requestFocus();
            sendConfigurationToLabeller(selectedConfIndex);
            updateLabellerConfigList();
        }
        startGlassTimer();
    }//GEN-LAST:event_sendConfButtonActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        glass.setVisible(true);
        padding.requestFocus();
        int selectedIndex = labellersComboBox.getSelectedIndex();
        if(selectedIndex == -1)
            return;
        chosenLabellerIPAddress = ((Labeller)labellersList.get(selectedIndex)).getIPAddress();
        int status = checkDBConnection();
        ((StatusPanel)connStatusPanel).updateStatus(status);
        if(status == 1)
        {
            updateLabellerConfigList();
            updateLabellerStats();
        }
        startGlassTimer();
    }//GEN-LAST:event_connectButtonActionPerformed

    private void disconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disconnectButtonActionPerformed
        disconnect();
    }//GEN-LAST:event_disconnectButtonActionPerformed

    private void downloadConfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadConfButtonActionPerformed
        int selectedIndex = labellerConfigListWindow.getSelectedIndex();
        if(selectedIndex == -1)
            return;
        if(ifConnected)
        {
            glass.setVisible(true);
            padding.requestFocus();
            downloadConfiguration(selectedIndex);
            updateComputerConfigList();
        }
        startGlassTimer();
    }//GEN-LAST:event_downloadConfButtonActionPerformed

    private void updateConfListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateConfListButtonActionPerformed
        if(ifConnected)
        {
            glass.setVisible(true);
            padding.requestFocus();
            updateLabellerConfigList();
        }
        startGlassTimer();
    }//GEN-LAST:event_updateConfListButtonActionPerformed

    private void startDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateTextFieldActionPerformed

    private void statsConfigListWindowValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_statsConfigListWindowValueChanged
        int selectedIndex = statsConfigListWindow.getSelectedIndex();
        if(selectedIndex != -1)
            displayStats(((ConfigurationStats)labellerConfigStatsList.get(selectedIndex)));
    }//GEN-LAST:event_statsConfigListWindowValueChanged

    private void updateStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStatsButtonActionPerformed
        if(ifConnected)
        {
            glass.setVisible(true);
            padding.requestFocus();
            updateLabellerStats();
        }
        startGlassTimer();
        int selectedIndex = statsConfigListWindow.getSelectedIndex();
        if(selectedIndex != -1)
            displayStats(((ConfigurationStats)labellerConfigStatsList.get(selectedIndex)));
    }//GEN-LAST:event_updateStatsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(labellerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(labellerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(labellerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(labellerApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new labellerApp().setVisible(true);
            }
        });
    }

    void updateLabellersComboBox()
    {
        labellersComboBox.removeAllItems();
        labellersList.clear();
        try {
            if(EditLabelersListWindow.labellersListFile.exists())
            {
               Scanner scanner = new Scanner(new BufferedReader(new FileReader(EditLabelersListWindow.labellersListFile)));
               while(scanner.hasNextLine())
               {
                   JSONObject labellerJson = new JSONObject(scanner.nextLine());
                   labellersList.add(new Labeller(labellerJson.getInt("id"), labellerJson.getString("name"), labellerJson.getString("IPAddress")));
                   labellersComboBox.addItem(new String(labellerJson.getString("name") + " (" + labellerJson.getString("IPAddress") + ")"));
               } 
               scanner.close();
            }
        } 
        catch (IOException ex) 
        {
            System.out.println("Path problem (updateLabellersComboBox)");
        }
    }
    
    private int checkDBConnection()
    {
        String DBUrl = new String("jdbc:mysql://" + chosenLabellerIPAddress + "/Etykieciarka");
        try
        {
            Class.forName(SQLDriver);
            connectionPool = ConnectionPool.create(DBUrl, DATABASE_USER, DATABASE_PASSWORD);
        }
        catch(SQLException ex)
        {
            System.out.println("SQL exception(checkDBConnection)");
            return -1;
        }  
        catch (ClassNotFoundException ex) 
        {
            System.out.println("Class exception(checkDBConnection)");
            return -1;
        }
        ifConnected = true;
        labellersComboBox.setEnabled(false);
        return 1;
    }
    
    private void updateComputerConfigList()
    {
        computerConfigListModel.clear();
        computerConfigList.clear();
        String[] list = CreateNewConfWindow.configurationsListDir.list();
        for(int i = 0; i < list.length; i++)
        {
            File file = new File(CreateNewConfWindow.configurationsListDir.getPath(), list[i]);
            String name = file.getName();
            if(name.substring(name.length()-8).equals(".labconf"))
            {
                try 
                {
                    Scanner scanner = new Scanner(new BufferedReader(new FileReader(file)));
                    if(scanner.hasNextLine())
                    {
                        JSONObject labellerJson = new JSONObject(scanner.nextLine());
                        computerConfigList.add(new Configuration(labellerJson.getInt("issuingVelocity"), labellerJson.getInt("ejectionDistance"), labellerJson.getInt("startRamp"), labellerJson.getInt("stopRamp"), labellerJson.getInt("startDelay"), labellerJson.getInt("stopDelay"), labellerJson.getDouble("velocityDifference"), labellerJson.getString("name")));
                        computerConfigListModel.addElement(name.substring(0, name.length()-8));
                    }    
                    scanner.close();
                } 
                catch (Exception ex) 
                {
                    System.out.println("Exception (updateComputerConfigList)");
                }
            }
        }
    }
    private void updateLabellerConfigList()
    {
        if(!ifConnected)
            return;
        Connection DBConn;
        try
        {
            DBConn = connectionPool.getConnection();
            String query = "SELECT * FROM programs";
            Statement statement = DBConn.createStatement();
            ResultSet results = statement.executeQuery(query);
            labellerConfigList.clear();
            labellerConfigListModel.clear();
            while(results.next())
            {
                int issuingVelocity = results.getInt("velocity_of_issuing_labels");
                int ejectionDistance = results.getInt("distance_of_label_ejection");
                int startRamp = results.getInt("start_ramp");
                int stopRamp = results.getInt("stop_ramp");
                int startDelay = results.getInt("stop_delay");
                int stopDelay = results.getInt("stop_delay");
                double velocityDifference = results.getDouble("velocity_difference");
                String name = results.getString("name");
                if(name == null)
                    continue;
                labellerConfigList.add(new Configuration(issuingVelocity, ejectionDistance, startRamp, stopRamp, startDelay, stopDelay, velocityDifference, name));
                labellerConfigListModel.addElement(labellerConfigList.get(labellerConfigList.size()-1));
            }
            connectionPool.releaseConnection(DBConn);
        } 
        catch (SQLException ex) 
        {
            System.out.println("SQL exception (updateLabellerConfigList)");
        } 
    }
    private void downloadConfiguration(int selectedIndex)
    {
        Configuration configuration = ((Configuration)labellerConfigList.get(selectedIndex));
        String configurationName = configuration.getName();
        String fileName = configurationName + ".labconf";
        File newConfiguration = new File(CreateNewConfWindow.configurationsListDir, fileName);
        int i = 1;
        while(newConfiguration.exists())
        {
            fileName = configurationName + "(" + i + ").labconf";
            i++;
            newConfiguration = new File(CreateNewConfWindow.configurationsListDir, fileName);
        }
        try {
            newConfiguration.createNewFile();
        } catch (IOException ex) {
            System.out.println("Creating new configuration file problem (downloadConfiguration)");
        }
        if(newConfiguration.exists())
        {
            try 
            {
                PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter(newConfiguration)));
                writer.println(prepareConfigJSONString(configuration));
                writer.close();
            } 
            catch (IOException ex) 
            {
                System.out.println("IO Exception (downloadConfiguration)");
            }
        }
    }
    
    private String prepareConfigJSONString(Configuration configuration)
    {
        String result = new String("{ \"issuingVelocity\" : " + configuration.getIssuingVelocity() + ", \"ejectionDistance\" : " 
                + configuration.getEjectionDistance() + ", \"startRamp\" : " + configuration.getStartRamp() + ", \"stopRamp\" : " 
                + configuration.getStopRamp() + ", \"startDelay\" : " + configuration.getStartDelay() + ", \"stopDelay\" : " 
                + configuration.getStopDelay() + ", \"velocityDifference\" : " + configuration.getVelocityDifference() 
                + ", \"name\" : \"" + configuration.getName() + "\" }");
        return result;
    }
    
    private void removeConfigurationFromLabeller(int selectedIndex)
    {
        Configuration configuration = ((Configuration)labellerConfigList.get(selectedIndex));
        String name = configuration.getName();
        Connection DBConn;
        try
        {
            DBConn = connectionPool.getConnection();
            String query = "delete from programs where name = ?";
            PreparedStatement preparedStmt = DBConn.prepareStatement(query);
            preparedStmt.setString(1, name);
            preparedStmt.execute();
            connectionPool.releaseConnection(DBConn);
            //labellerConfigListModel.remove(selectedIndex);
            //labellerConfigList.remove(selectedIndex);
        } 
        catch (SQLException ex) 
        {
            System.out.println("SQL exception (removeConfigurationFromLabeller)");
        }  
    }
    
    private void sendConfigurationToLabeller(int selectedIndex)
    {
        updateLabellerConfigList();
        Configuration configuration = ((Configuration)computerConfigList.get(selectedIndex));
        Connection DBConn;
        String name = configuration.getName();
        boolean isCorrect = false;
        int addToName = 1;
        //Check if name isn't already used in database
        while(!isCorrect)
        {
            int check = addToName;
            for(int i = 0; i < labellerConfigList.size(); i++)
            {
                if(name.equals(((Configuration)labellerConfigList.get(i)).getName()))
                {
                    name = name + "(" + addToName + ")";
                    addToName++;
                }
            }
            if(check == addToName)
                isCorrect = true;
        }
        try
        {
            DBConn = connectionPool.getConnection();
            String query = " insert into programs (velocity_of_issuing_labels, distance_of_label_ejection, start_ramp, stop_ramp, start_delay, stop_delay, velocity_difference, name)"
            + " values (?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement preparedStmt = DBConn.prepareStatement(query);
            preparedStmt.setInt(1, configuration.getIssuingVelocity());
            preparedStmt.setInt(2, configuration.getEjectionDistance());
            preparedStmt.setInt(3, configuration.getStartRamp());
            preparedStmt.setInt(4, configuration.getStopRamp());
            preparedStmt.setInt(5, configuration.getStartDelay());
            preparedStmt.setInt(6, configuration.getStopDelay());
            preparedStmt.setDouble(7, configuration.getVelocityDifference());
            preparedStmt.setString(8, name);
            preparedStmt.execute();
            connectionPool.releaseConnection(DBConn);
        } 
        catch (SQLException ex) 
        {
            System.out.println("SQL exception (sendConfigurationToLabeller)");
        } 
    }
    
    private void updateLabellerStats()
    {
        if(!ifConnected)
            return;
        Connection DBConn;
        try
        {
            DBConn = connectionPool.getConnection();
            String query = "SELECT * FROM programs_history";
            Statement statement = DBConn.createStatement();
            ResultSet results = statement.executeQuery(query);
            labellerConfigStatsList.clear();
            labellerConfigStatsListModel.clear();
            while(results.next())
            {
                Timestamp startDate = Optional.ofNullable(results.getTimestamp("start_date")).orElse(new Timestamp(0));
                Timestamp stopDate = Optional.ofNullable(results.getTimestamp("stop_date")).orElse(new Timestamp(0));
                int information1 = Optional.ofNullable(results.getInt("information #1")).orElse(0);
                int information2 = Optional.ofNullable(results.getInt("information #2")).orElse(0);
                int information3 = Optional.ofNullable(results.getInt("information #3")).orElse(0);
                String name = Optional.ofNullable(results.getString("program_name")).orElse("---------");
                labellerConfigStatsList.add(new ConfigurationStats(startDate, stopDate, information1, information2, information3, name));
                labellerConfigStatsListModel.addElement(labellerConfigStatsList.get(labellerConfigStatsList.size()-1));
            }
            connectionPool.releaseConnection(DBConn);
        } 
        catch (SQLException ex) 
        {
            System.out.println("SQL exception (updateLabellerStats)");
        }
    }
    
    private void displayStats(ConfigurationStats configStats)
    {
        startDateTextField.setText(configStats.getStartDate().toString());
        stopDateTextField.setText(configStats.getStopDate().toString());
        info1TextField.setText(""+configStats.getInformation1());
        info2TextField.setText(""+configStats.getInformation2());
        info3TextField.setText(""+configStats.getInformation3());
    }
    
    private void displayStats(String text)
    {
        startDateTextField.setText(text);
        stopDateTextField.setText(text);
        info1TextField.setText(text);
        info2TextField.setText(text);
        info3TextField.setText(text);
    }
    
    private void disconnect()
    {
        ((StatusPanel)connStatusPanel).updateStatus(0);
        ifConnected = false;
        labellerConfigList.clear();
        labellerConfigListModel.clear();
        labellerConfigStatsList.clear();
        labellerConfigStatsListModel.clear();
        displayStats("");
        labellersComboBox.setEnabled(true);
        if(connectionPool != null)
        {
            try 
            {
                connectionPool.shutdown();
            } 
            catch (SQLException ex) 
            {
                System.out.println("SQL exception (shutting down connection pool)");
            }
        }
    }

    private void startGlassTimer() 
    {  
        if (timer == null) {
            timer = new Timer(100, new ActionListener() {
                int progress = 0;
                public void actionPerformed(ActionEvent A) {
                    progress += 10;
                    if (progress >= 100) {
                        progress = 0;
                        timer.stop();
                        glass.setVisible(false);
                    }
                }
            });
        } 
        if (timer.isRunning()) {
            timer.stop();
        } 
        timer.start();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> computerConfigListWindow;
    private javax.swing.JPanel confPanel;
    private javax.swing.JTabbedPane confStatsPane;
    private javax.swing.JPanel connStatusPanel;
    private javax.swing.JButton connectButton;
    private javax.swing.JPanel connectPanel;
    private javax.swing.JButton disconnectButton;
    private javax.swing.JButton downloadConfButton;
    private javax.swing.JButton editConfButton;
    private javax.swing.JButton editLabListButton;
    private javax.swing.JTextField info1TextField;
    private javax.swing.JTextField info2TextField;
    private javax.swing.JTextField info3TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> labellerConfigListWindow;
    private javax.swing.JComboBox<String> labellersComboBox;
    private javax.swing.JButton newConfButton;
    private javax.swing.JButton removeCompConfButton;
    private javax.swing.JButton removeLabelConfButton;
    private javax.swing.JButton sendConfButton;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JList<String> statsConfigListWindow;
    private javax.swing.JPanel statsPanel;
    private javax.swing.JTextField stopDateTextField;
    private javax.swing.JButton updateConfListButton;
    private javax.swing.JButton updateStatsButton;
    // End of variables declaration//GEN-END:variables
}
class StatusPanel extends JPanel
{
    private Image icon = new ImageIcon("question mark.png").getImage();
    public StatusPanel()
    {
        super();
    }
    public void updateStatus(int status)
    {
        if(status == 1)
            icon = new ImageIcon("ok.png").getImage();
        else if(status == -1)
            icon = new ImageIcon("wrong.png").getImage();
        else if(status == 0)
            icon = new ImageIcon("question mark.png").getImage();
        this.repaint();
    }
    @Override
    public void paintComponent(Graphics g)
    {
        super.paintComponent(g);
        g.drawImage(icon, (this.getWidth()-icon.getWidth(this))/2, 1, null);
    }
}